/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-02-04 17:47:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/pages/common/head.jspf", Long.valueOf(1733414778000L));
    _jspx_dependants.put("/WEB-INF/pages/common/sidebarnonlogin.jspf", Long.valueOf(1733414778000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1727442631000L));
    _jspx_dependants.put("jar:file:/home/adrian/Documents/IUCOSOFT/UpdateOfTheUpdateUPDATE/JvavaWveb/target/JvavaWveb-1.0-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/pages/common/meniu.jspf", Long.valueOf(1733414778000L));
    _jspx_dependants.put("/WEB-INF/pages/common/footer.jspf", Long.valueOf(1733414778000L));
    _jspx_dependants.put("/WEB-INF/pages/common/footerscripts.jspf", Long.valueOf(1733414778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        ");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../resources/styles/styles.css\">\n");
      out.write("<link rel=\"icon\" href=\"#\" type=\"image/gif\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" \n");
      out.write("      rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" \n");
      out.write("      crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <title>DayNest</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            html, body{\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                /*margin: 0;*/\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                padding-top: 60px;\r\n");
      out.write("                background-color: #121212;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                font-family: 'Arial', sans-serif;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar {\r\n");
      out.write("                background-color: #1f1f1f;\r\n");
      out.write("                box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.5); \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar-brand, .navbar-nav .nav-link {\r\n");
      out.write("                color: #00aaff !important;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar-brand:hover, .navbar-nav .nav-link:hover {\r\n");
      out.write("                color: #00cfff !important;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .offcanvas-sidebar {\r\n");
      out.write("                width: 20%;\r\n");
      out.write("                background-color: #1f1f1f;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .offcanvas-sidebar .list-group-item {\r\n");
      out.write("                background-color: #2c2c2c;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                border: none;\r\n");
      out.write("                padding: 10px 20px;\r\n");
      out.write("                cursor: not-allowed;\r\n");
      out.write("                opacity: 0.5;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-panel {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                justify-content: flex-start;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                padding-right: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-panel button {\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("                background-color: #2c2c2c;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                border: 1px solid #e0e0e0;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-panel button:hover {\r\n");
      out.write("                background-color: #00aaff;\r\n");
      out.write("                color: white;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card {\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card .card {\r\n");
      out.write("                background-color: #333;\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card .weather-description {\r\n");
      out.write("                background-color: #2b2b2b;\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                margin-top: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card img {\r\n");
      out.write("                border-radius: 8px 8px 0 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-description p {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                color: #ccc;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-message {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 20px;\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                color: #ff6347;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-success {\r\n");
      out.write("                background-color: #00aaff;\r\n");
      out.write("                border-color: #00aaff;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-success:hover {\r\n");
      out.write("                background-color: #00cfff;\r\n");
      out.write("                border-color: #00cfff;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-outline-success {\r\n");
      out.write("                color: #00aaff;\r\n");
      out.write("                border-color: #00aaff;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-outline-success:hover {\r\n");
      out.write("                color: #00cfff;\r\n");
      out.write("                border-color: #00cfff;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card {\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("                background-color: #2c2c2c;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("                transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card:hover {\r\n");
      out.write("                transform: translateY(-10px);\r\n");
      out.write("                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card-img-top {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: auto; \r\n");
      out.write("                object-fit: contain; \r\n");
      out.write("                border-bottom: 1px solid #2c2c2c;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .footer {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                background-color: #1f1f1f;\r\n");
      out.write("                color: #e0e0e0;\r\n");
      out.write("                padding: 20px 0;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                margin-top: auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container.content {\r\n");
      out.write("                margin-top: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .content{\r\n");
      out.write("                flex: 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card-modern {\r\n");
      out.write("                background: linear-gradient(135deg, #00aaff, #00cfff);\r\n");
      out.write("                color: white;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card-modern:hover {\r\n");
      out.write("                transform: translateY(-5px);\r\n");
      out.write("                box-shadow: 0 8px 20px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-header {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                margin-bottom: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-location {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-icon {\r\n");
      out.write("                width: 50px;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-body {\r\n");
      out.write("                margin: 20px 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-temp {\r\n");
      out.write("                font-size: 3rem;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-description {\r\n");
      out.write("                font-size: 1.2rem;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("                color: #f0f0f0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-footer {\r\n");
      out.write("                margin-top: 15px;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("                opacity: 0.8;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-panel button {\r\n");
      out.write("                display: block;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                margin: 10px 0;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                background: #444;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                transition: background 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-panel button:hover {\r\n");
      out.write("                background: #666;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-card-modern {\r\n");
      out.write("                background: #2d2d2d;\r\n");
      out.write("                color: white;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-header {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-icon {\r\n");
      out.write("                width: 50px;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-body {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .weather-footer {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                color: #aaa;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <button class=\"btn btn-secondary\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasSidebar\" aria-controls=\"offcanvasSidebar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <a class=\"navbar-brand ms-3\" href=\"/\">DayNest</a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarContent\" aria-controls=\"navbarContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarContent\">\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"discover.html\">Discover</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"about.html\">About Us</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("                        Explore Your Favourite Categories\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Favourite 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Favourite 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Favourite 3</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">En</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link disabled\" aria-current=\"page\" href=\"#\">|</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Ro</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <form class=\"d-flex ms-3\" role=\"search\">\n");
      out.write("                <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("                <button class=\"btn btn-success\" type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("            <form class=\"d-flex ms-3\">\n");
      out.write("                <a href=\"/login.html\">\n");
      out.write("                    <button class=\"btn btn-outline-success\" type=\"button\">Log In</button>\n");
      out.write("                </a>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("<div class=\"offcanvas offcanvas-start offcanvas-sidebar\" tabindex=\"-1\" id=\"offcanvasSidebar\" aria-labelledby=\"offcanvasSidebarLabel\">\n");
      out.write("    <div class=\"offcanvas-header\">\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"offcanvasSidebarLabel\">Your Settings</h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"offcanvas-body\">\n");
      out.write("        <div class=\"login-message\">\n");
      out.write("            <p>Login required to access these options.</p>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"list-group\">\n");
      out.write("            <li class=\"list-group-item disabled\">My Profile</li>\n");
      out.write("            <li class=\"list-group-item disabled\">Manage my Posts</li>\n");
      out.write("            <li class=\"list-group-item disabled\">\n");
      out.write("                <form class=\"d-flex mt-3\" role=\"search\">\n");
      out.write("                    <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("                    <button class=\"btn btn-success\" type=\"submit\">Search In Your Posts</button>\n");
      out.write("                </form>\n");
      out.write("            <li>\n");
      out.write("        </ul>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-grid\" style=\"position: absolute;\">\n");
      out.write("            <a href=\"/login.html\">\n");
      out.write("                <button class=\"btn btn-outline-success\" type=\"button\">Log In</button>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container content\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 btn-panel\">\r\n");
      out.write("                            <button data-category=\"temperature\">Temperature</button>\r\n");
      out.write("                            <button data-category=\"wind\">Wind</button>\r\n");
      out.write("                            <button data-category=\"air-masses\">Air Masses</button>\r\n");
      out.write("                            <button data-category=\"precipitations\">Precipitations</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-9 weather-card\">\r\n");
      out.write("                            <div class=\"card weather-card-modern\">\r\n");
      out.write("                                <div class=\"weather-header\">\r\n");
      out.write("                                    <h5 class=\"weather-location\">Loading...</h5> \r\n");
      out.write("                                    <img src=\"https://openweathermap.org/img/wn/01d@2x.png\" alt=\"Sunny\" class=\"weather-icon\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"weather-body\">\r\n");
      out.write("                                    <h1 class=\"weather-temp\">--°C</h1> \r\n");
      out.write("                                    <p class=\"weather-description\">Loading...</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"weather-details\" class=\"weather-footer\">\r\n");
      out.write("                                    <p class=\"weather-details\">Humidity: --% | Wind: -- km/h</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-12 text-center my-4\">\r\n");
      out.write("                            <button id=\"get-location\" class=\"btn btn-success\">Show My Location</button>\r\n");
      out.write("                            <div id=\"location-display\" class=\"mt-3\">\r\n");
      out.write("                                <p id=\"latitude\">Latitude: --</p>\r\n");
      out.write("                                <p id=\"longitude\">Longitude: --</p>\r\n");
      out.write("                                <p id=\"accuracy\">Accuracy: -- meters</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <nav aria-label=\"Page navigation\">\r\n");
      out.write("                        <ul class=\"pagination justify-content-center\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("<div class=\"footer\" style=\"position: absolute; bottom: 0; left: 0; right: 0\">\n");
      out.write("    &copy; 2024 DayNest. All rights reserved.\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("    document.getElementById(\"get-location\").addEventListener(\"click\", function () {\r\n");
      out.write("        if (navigator.geolocation) {\r\n");
      out.write("            navigator.geolocation.getCurrentPosition(\r\n");
      out.write("                function (position) {\r\n");
      out.write("                    document.getElementById(\"latitude\").innerText = \"Latitude: \" + position.coords.latitude;\r\n");
      out.write("                    document.getElementById(\"longitude\").innerText = \"Longitude: \" + position.coords.longitude;\r\n");
      out.write("                    document.getElementById(\"accuracy\").innerText = \"Accuracy: \" + position.coords.accuracy + \" meters\";\r\n");
      out.write("                },\r\n");
      out.write("                function (error) {\r\n");
      out.write("                    let errorMessage = \"An error occurred while retrieving your location.\";\r\n");
      out.write("                    switch (error.code) {\r\n");
      out.write("                        case error.PERMISSION_DENIED:\r\n");
      out.write("                            errorMessage = \"Permission denied. Please allow location access.\";\r\n");
      out.write("                            break;\r\n");
      out.write("                        case error.POSITION_UNAVAILABLE:\r\n");
      out.write("                            errorMessage = \"Location information is unavailable.\";\r\n");
      out.write("                            break;\r\n");
      out.write("                        case error.TIMEOUT:\r\n");
      out.write("                            errorMessage = \"Location request timed out.\";\r\n");
      out.write("                            break;\r\n");
      out.write("                    }\r\n");
      out.write("                    alert(errorMessage);\r\n");
      out.write("                }\r\n");
      out.write("            );\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"Geolocation is not supported by your browser.\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" \n");
      out.write("        integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" \n");
      out.write("        crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" \n");
      out.write("        integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" \n");
      out.write("        crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/index.jsp(330,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/index.jsp(330,24) '${postList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${postList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/index.jsp(330,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("post");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            <div class=\"col-lg-6\">\r\n");
            out.write("                                <div class=\"card\">\r\n");
            out.write("                                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"card-img-top\" alt=\"Card Image\">\r\n");
            out.write("                                    <div class=\"card-body\">\r\n");
            out.write("                                        <h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                                        <p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                                        <a href=\"#\" class=\"btn btn-success\">Read more</a>\r\n");
            out.write("                                        <h6>Posted by ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.userId.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/pages/index.jsp(347,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      // /WEB-INF/pages/index.jsp(347,28) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/pages/index.jsp(347,28) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noOfPages}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <li class=\"page-item ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i == currentPage ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                    <a class=\"page-link\" href=\"/?page=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("                                </li>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
